image: alpine-edge
arch: x86_64
packages:
 - git
 - clang
 - cmake
 - build-base
 - ninja
 - autoconf
 - libtool
 - texinfo
 - gettext-dev
 - libexecinfo-dev
 - gtest

sources:
 - https://github.com/dukeify/fake-jni/tree/sr_ht_ci

environment:
 CC: clang
 CXX: clang++

tasks:
 - setup: |
  mkdir build
  cd build
  cmake ../ -GNinja -DBUILD_FAKE_JNI_DEBUG=ON
 - compile: |
  ninja -j0
 - test: |
  ./build/test/jni-test
 
